/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.author.dto;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BookCategory implements Serializable
{

    private static final long serialVersionUID = 1L;

    private Long id;
    private String title;
    private Integer sortPosition;
    private Byte isDeleted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public BookCategory()
    {
    }

    public BookCategory(BookCategory value)
    {
        this.id = value.id;
        this.title = value.title;
        this.sortPosition = value.sortPosition;
        this.isDeleted = value.isDeleted;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public BookCategory(
            Long id,
            String title,
            Integer sortPosition,
            Byte isDeleted,
            LocalDateTime createdAt,
            LocalDateTime updatedAt
    )
    {
        this.id = id;
        this.title = title;
        this.sortPosition = sortPosition;
        this.isDeleted = isDeleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>polaris-db.book_category.id</code>.
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * Setter for <code>polaris-db.book_category.id</code>.
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * Getter for <code>polaris-db.book_category.title</code>. 書本分類名稱
     */
    public String getTitle()
    {
        return this.title;
    }

    /**
     * Setter for <code>polaris-db.book_category.title</code>. 書本分類名稱
     */
    public void setTitle(String title)
    {
        this.title = title;
    }

    /**
     * Getter for <code>polaris-db.book_category.sort_position</code>. 排序位置
     */
    public Integer getSortPosition()
    {
        return this.sortPosition;
    }

    /**
     * Setter for <code>polaris-db.book_category.sort_position</code>. 排序位置
     */
    public void setSortPosition(Integer sortPosition)
    {
        this.sortPosition = sortPosition;
    }

    /**
     * Getter for <code>polaris-db.book_category.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public Byte getIsDeleted()
    {
        return this.isDeleted;
    }

    /**
     * Setter for <code>polaris-db.book_category.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public void setIsDeleted(Byte isDeleted)
    {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>polaris-db.book_category.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt()
    {
        return this.createdAt;
    }

    /**
     * Setter for <code>polaris-db.book_category.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime createdAt)
    {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>polaris-db.book_category.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt()
    {
        return this.updatedAt;
    }

    /**
     * Setter for <code>polaris-db.book_category.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime updatedAt)
    {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("BookCategory (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(sortPosition);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
