/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.author.dto;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class User implements Serializable
{

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String uid;
    private String password;
    private String email;
    private String avatar;
    private String shortBio;
    private String fullBio;
    private LocalDate birthday;
    private Byte isAuthor;
    private String twitter;
    private String github;
    private String linkedin;
    private String facebook;
    private Byte isBlocked;
    private Byte isDeleted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public User()
    {
    }

    public User(User value)
    {
        this.id = value.id;
        this.name = value.name;
        this.uid = value.uid;
        this.password = value.password;
        this.email = value.email;
        this.avatar = value.avatar;
        this.shortBio = value.shortBio;
        this.fullBio = value.fullBio;
        this.birthday = value.birthday;
        this.isAuthor = value.isAuthor;
        this.twitter = value.twitter;
        this.github = value.github;
        this.linkedin = value.linkedin;
        this.facebook = value.facebook;
        this.isBlocked = value.isBlocked;
        this.isDeleted = value.isDeleted;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public User(
            Long id,
            String name,
            String uid,
            String password,
            String email,
            String avatar,
            String shortBio,
            String fullBio,
            LocalDate birthday,
            Byte isAuthor,
            String twitter,
            String github,
            String linkedin,
            String facebook,
            Byte isBlocked,
            Byte isDeleted,
            LocalDateTime createdAt,
            LocalDateTime updatedAt
    )
    {
        this.id = id;
        this.name = name;
        this.uid = uid;
        this.password = password;
        this.email = email;
        this.avatar = avatar;
        this.shortBio = shortBio;
        this.fullBio = fullBio;
        this.birthday = birthday;
        this.isAuthor = isAuthor;
        this.twitter = twitter;
        this.github = github;
        this.linkedin = linkedin;
        this.facebook = facebook;
        this.isBlocked = isBlocked;
        this.isDeleted = isDeleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>polaris-db.user.id</code>.
     */
    public Long getId()
    {
        return this.id;
    }

    /**
     * Setter for <code>polaris-db.user.id</code>.
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * Getter for <code>polaris-db.user.name</code>. 使用者名稱
     */
    public String getName()
    {
        return this.name;
    }

    /**
     * Setter for <code>polaris-db.user.name</code>. 使用者名稱
     */
    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * Getter for <code>polaris-db.user.uid</code>. 使用者 Uid
     */
    public String getUid()
    {
        return this.uid;
    }

    /**
     * Setter for <code>polaris-db.user.uid</code>. 使用者 Uid
     */
    public void setUid(String uid)
    {
        this.uid = uid;
    }

    /**
     * Getter for <code>polaris-db.user.password</code>. 使用者密碼
     */
    public String getPassword()
    {
        return this.password;
    }

    /**
     * Setter for <code>polaris-db.user.password</code>. 使用者密碼
     */
    public void setPassword(String password)
    {
        this.password = password;
    }

    /**
     * Getter for <code>polaris-db.user.email</code>. 使用者 E-mail
     */
    public String getEmail()
    {
        return this.email;
    }

    /**
     * Setter for <code>polaris-db.user.email</code>. 使用者 E-mail
     */
    public void setEmail(String email)
    {
        this.email = email;
    }

    /**
     * Getter for <code>polaris-db.user.avatar</code>. 使用者頭像
     */
    public String getAvatar()
    {
        return this.avatar;
    }

    /**
     * Setter for <code>polaris-db.user.avatar</code>. 使用者頭像
     */
    public void setAvatar(String avatar)
    {
        this.avatar = avatar;
    }

    /**
     * Getter for <code>polaris-db.user.short_bio</code>. 使用者簡短介紹
     */
    public String getShortBio()
    {
        return this.shortBio;
    }

    /**
     * Setter for <code>polaris-db.user.short_bio</code>. 使用者簡短介紹
     */
    public void setShortBio(String shortBio)
    {
        this.shortBio = shortBio;
    }

    /**
     * Getter for <code>polaris-db.user.full_bio</code>. 使用者完整介紹
     */
    public String getFullBio()
    {
        return this.fullBio;
    }

    /**
     * Setter for <code>polaris-db.user.full_bio</code>. 使用者完整介紹
     */
    public void setFullBio(String fullBio)
    {
        this.fullBio = fullBio;
    }

    /**
     * Getter for <code>polaris-db.user.birthday</code>. 使用者生日
     */
    public LocalDate getBirthday()
    {
        return this.birthday;
    }

    /**
     * Setter for <code>polaris-db.user.birthday</code>. 使用者生日
     */
    public void setBirthday(LocalDate birthday)
    {
        this.birthday = birthday;
    }

    /**
     * Getter for <code>polaris-db.user.is_author</code>. 是否是作者，0-否，1-是，預設為 0
     */
    public Byte getIsAuthor()
    {
        return this.isAuthor;
    }

    /**
     * Setter for <code>polaris-db.user.is_author</code>. 是否是作者，0-否，1-是，預設為 0
     */
    public void setIsAuthor(Byte isAuthor)
    {
        this.isAuthor = isAuthor;
    }

    /**
     * Getter for <code>polaris-db.user.twitter</code>.
     */
    public String getTwitter()
    {
        return this.twitter;
    }

    /**
     * Setter for <code>polaris-db.user.twitter</code>.
     */
    public void setTwitter(String twitter)
    {
        this.twitter = twitter;
    }

    /**
     * Getter for <code>polaris-db.user.github</code>.
     */
    public String getGithub()
    {
        return this.github;
    }

    /**
     * Setter for <code>polaris-db.user.github</code>.
     */
    public void setGithub(String github)
    {
        this.github = github;
    }

    /**
     * Getter for <code>polaris-db.user.linkedin</code>.
     */
    public String getLinkedin()
    {
        return this.linkedin;
    }

    /**
     * Setter for <code>polaris-db.user.linkedin</code>.
     */
    public void setLinkedin(String linkedin)
    {
        this.linkedin = linkedin;
    }

    /**
     * Getter for <code>polaris-db.user.facebook</code>.
     */
    public String getFacebook()
    {
        return this.facebook;
    }

    /**
     * Setter for <code>polaris-db.user.facebook</code>.
     */
    public void setFacebook(String facebook)
    {
        this.facebook = facebook;
    }

    /**
     * Getter for <code>polaris-db.user.is_blocked</code>. 是否停權，0-否，1-是，預設為 0
     */
    public Byte getIsBlocked()
    {
        return this.isBlocked;
    }

    /**
     * Setter for <code>polaris-db.user.is_blocked</code>. 是否停權，0-否，1-是，預設為 0
     */
    public void setIsBlocked(Byte isBlocked)
    {
        this.isBlocked = isBlocked;
    }

    /**
     * Getter for <code>polaris-db.user.is_deleted</code>. 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public Byte getIsDeleted()
    {
        return this.isDeleted;
    }

    /**
     * Setter for <code>polaris-db.user.is_deleted</code>. 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public void setIsDeleted(Byte isDeleted)
    {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>polaris-db.user.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt()
    {
        return this.createdAt;
    }

    /**
     * Setter for <code>polaris-db.user.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime createdAt)
    {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>polaris-db.user.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt()
    {
        return this.updatedAt;
    }

    /**
     * Setter for <code>polaris-db.user.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime updatedAt)
    {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(uid);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(avatar);
        sb.append(", ").append(shortBio);
        sb.append(", ").append(fullBio);
        sb.append(", ").append(birthday);
        sb.append(", ").append(isAuthor);
        sb.append(", ").append(twitter);
        sb.append(", ").append(github);
        sb.append(", ").append(linkedin);
        sb.append(", ").append(facebook);
        sb.append(", ").append(isBlocked);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
