/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.model.tables.records;


import com.bcorp.polaris.core.model.tables.BookCategory;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookCategoryRecord extends UpdatableRecordImpl<BookCategoryRecord> implements Record8<Long, String, Long, Integer, Byte, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>polaris-db.book_category.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>polaris-db.book_category.name</code>. 書本分類名稱
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.name</code>. 書本分類名稱
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>polaris-db.book_category.parent_id</code>. 父類別 id
     */
    public void setParentId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.parent_id</code>. 父類別 id
     */
    public Long getParentId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>polaris-db.book_category.sort_position</code>. 排序位置
     */
    public void setSortPosition(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.sort_position</code>. 排序位置
     */
    public Integer getSortPosition() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>polaris-db.book_category.is_visible</code>.
     * 是否顯示前台，0-否，1-是，預設為 0
     */
    public void setIsVisible(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.is_visible</code>.
     * 是否顯示前台，0-否，1-是，預設為 0
     */
    public Byte getIsVisible() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>polaris-db.book_category.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public void setIsDeleted(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public Byte getIsDeleted() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>polaris-db.book_category.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>polaris-db.book_category.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, Long, Integer, Byte, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, Long, Integer, Byte, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BookCategory.BOOK_CATEGORY.ID;
    }

    @Override
    public Field<String> field2() {
        return BookCategory.BOOK_CATEGORY.NAME;
    }

    @Override
    public Field<Long> field3() {
        return BookCategory.BOOK_CATEGORY.PARENT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return BookCategory.BOOK_CATEGORY.SORT_POSITION;
    }

    @Override
    public Field<Byte> field5() {
        return BookCategory.BOOK_CATEGORY.IS_VISIBLE;
    }

    @Override
    public Field<Byte> field6() {
        return BookCategory.BOOK_CATEGORY.IS_DELETED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return BookCategory.BOOK_CATEGORY.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return BookCategory.BOOK_CATEGORY.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getParentId();
    }

    @Override
    public Integer component4() {
        return getSortPosition();
    }

    @Override
    public Byte component5() {
        return getIsVisible();
    }

    @Override
    public Byte component6() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getParentId();
    }

    @Override
    public Integer value4() {
        return getSortPosition();
    }

    @Override
    public Byte value5() {
        return getIsVisible();
    }

    @Override
    public Byte value6() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public BookCategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BookCategoryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public BookCategoryRecord value3(Long value) {
        setParentId(value);
        return this;
    }

    @Override
    public BookCategoryRecord value4(Integer value) {
        setSortPosition(value);
        return this;
    }

    @Override
    public BookCategoryRecord value5(Byte value) {
        setIsVisible(value);
        return this;
    }

    @Override
    public BookCategoryRecord value6(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public BookCategoryRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public BookCategoryRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public BookCategoryRecord values(Long value1, String value2, Long value3, Integer value4, Byte value5, Byte value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookCategoryRecord
     */
    public BookCategoryRecord() {
        super(BookCategory.BOOK_CATEGORY);
    }

    /**
     * Create a detached, initialised BookCategoryRecord
     */
    public BookCategoryRecord(Long id, String name, Long parentId, Integer sortPosition, Byte isVisible, Byte isDeleted, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(BookCategory.BOOK_CATEGORY);

        setId(id);
        setName(name);
        setParentId(parentId);
        setSortPosition(sortPosition);
        setIsVisible(isVisible);
        setIsDeleted(isDeleted);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
