/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.model.tables.records;


import com.bcorp.polaris.core.model.tables.BookCategoryRel;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookCategoryRelRecord extends UpdatableRecordImpl<BookCategoryRelRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>polaris-db.book_category_rel.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>polaris-db.book_category_rel.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>polaris-db.book_category_rel.book_id</code>.
     */
    public void setBookId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>polaris-db.book_category_rel.book_id</code>.
     */
    public Long getBookId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>polaris-db.book_category_rel.book_category_id</code>.
     */
    public void setBookCategoryId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>polaris-db.book_category_rel.book_category_id</code>.
     */
    public Long getBookCategoryId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BookCategoryRel.BOOK_CATEGORY_REL.ID;
    }

    @Override
    public Field<Long> field2() {
        return BookCategoryRel.BOOK_CATEGORY_REL.BOOK_ID;
    }

    @Override
    public Field<Long> field3() {
        return BookCategoryRel.BOOK_CATEGORY_REL.BOOK_CATEGORY_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getBookId();
    }

    @Override
    public Long component3() {
        return getBookCategoryId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getBookId();
    }

    @Override
    public Long value3() {
        return getBookCategoryId();
    }

    @Override
    public BookCategoryRelRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BookCategoryRelRecord value2(Long value) {
        setBookId(value);
        return this;
    }

    @Override
    public BookCategoryRelRecord value3(Long value) {
        setBookCategoryId(value);
        return this;
    }

    @Override
    public BookCategoryRelRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookCategoryRelRecord
     */
    public BookCategoryRelRecord() {
        super(BookCategoryRel.BOOK_CATEGORY_REL);
    }

    /**
     * Create a detached, initialised BookCategoryRelRecord
     */
    public BookCategoryRelRecord(Long id, Long bookId, Long bookCategoryId) {
        super(BookCategoryRel.BOOK_CATEGORY_REL);

        setId(id);
        setBookId(bookId);
        setBookCategoryId(bookCategoryId);
    }
}
