/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.model.tables.records;


import com.bcorp.polaris.core.model.tables.BookCategory;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookCategoryRecord extends UpdatableRecordImpl<BookCategoryRecord> implements Record6<Long, String, Integer, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>polaris-db.book_category.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>polaris-db.book_category.title</code>. 書本分類名稱
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.title</code>. 書本分類名稱
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>polaris-db.book_category.sort_position</code>. 排序位置
     */
    public void setSortPosition(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.sort_position</code>. 排序位置
     */
    public Integer getSortPosition() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>polaris-db.book_category.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public void setIsDeleted(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public Byte getIsDeleted() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>polaris-db.book_category.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>polaris-db.book_category.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>polaris-db.book_category.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Integer, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Integer, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BookCategory.BOOK_CATEGORY.ID;
    }

    @Override
    public Field<String> field2() {
        return BookCategory.BOOK_CATEGORY.TITLE;
    }

    @Override
    public Field<Integer> field3() {
        return BookCategory.BOOK_CATEGORY.SORT_POSITION;
    }

    @Override
    public Field<Byte> field4() {
        return BookCategory.BOOK_CATEGORY.IS_DELETED;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return BookCategory.BOOK_CATEGORY.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return BookCategory.BOOK_CATEGORY.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public Integer component3() {
        return getSortPosition();
    }

    @Override
    public Byte component4() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public Integer value3() {
        return getSortPosition();
    }

    @Override
    public Byte value4() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public BookCategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BookCategoryRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public BookCategoryRecord value3(Integer value) {
        setSortPosition(value);
        return this;
    }

    @Override
    public BookCategoryRecord value4(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public BookCategoryRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public BookCategoryRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public BookCategoryRecord values(Long value1, String value2, Integer value3, Byte value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookCategoryRecord
     */
    public BookCategoryRecord() {
        super(BookCategory.BOOK_CATEGORY);
    }

    /**
     * Create a detached, initialised BookCategoryRecord
     */
    public BookCategoryRecord(Long id, String title, Integer sortPosition, Byte isDeleted, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(BookCategory.BOOK_CATEGORY);

        setId(id);
        setTitle(title);
        setSortPosition(sortPosition);
        setIsDeleted(isDeleted);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
