/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.model.tables.records;


import com.bcorp.polaris.core.model.tables.CartLineItem;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CartLineItemRecord extends UpdatableRecordImpl<CartLineItemRecord> implements Record13<Long, Long, Long, String, BigDecimal, String, String, Byte, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>polaris-db.cart_line_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.cart_id</code>. 購物車 id
     */
    public void setCartId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.cart_id</code>. 購物車 id
     */
    public Long getCartId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.book_id</code>.
     */
    public void setBookId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.book_id</code>.
     */
    public Long getBookId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.name</code>. 商品名稱
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.name</code>. 商品名稱
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.price</code>. 商品金額
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.price</code>. 商品金額
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.cover</code>. 書封
     */
    public void setCover(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.cover</code>. 書封
     */
    public String getCover() {
        return (String) get(5);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.item_key</code>.
     * book_id:(name,price) 用來判斷資料是否改變
     */
    public void setItemKey(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.item_key</code>.
     * book_id:(name,price) 用來判斷資料是否改變
     */
    public String getItemKey() {
        return (String) get(6);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.status</code>.
     * 商品狀態，0-未上架，1-已上架，預設為 1
     */
    public void setStatus(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.status</code>.
     * 商品狀態，0-未上架，1-已上架，預設為 1
     */
    public Byte getStatus() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.subtotal</code>. 商品小計
     */
    public void setSubtotal(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.subtotal</code>. 商品小計
     */
    public BigDecimal getSubtotal() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.total_discounts</code>. 商品總折扣
     */
    public void setTotalDiscounts(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.total_discounts</code>. 商品總折扣
     */
    public BigDecimal getTotalDiscounts() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.total_price</code>. 商品總金額
     */
    public void setTotalPrice(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.total_price</code>. 商品總金額
     */
    public BigDecimal getTotalPrice() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>polaris-db.cart_line_item.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>polaris-db.cart_line_item.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, Long, Long, String, BigDecimal, String, String, Byte, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, Long, Long, String, BigDecimal, String, String, Byte, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CartLineItem.CART_LINE_ITEM.ID;
    }

    @Override
    public Field<Long> field2() {
        return CartLineItem.CART_LINE_ITEM.CART_ID;
    }

    @Override
    public Field<Long> field3() {
        return CartLineItem.CART_LINE_ITEM.BOOK_ID;
    }

    @Override
    public Field<String> field4() {
        return CartLineItem.CART_LINE_ITEM.NAME;
    }

    @Override
    public Field<BigDecimal> field5() {
        return CartLineItem.CART_LINE_ITEM.PRICE;
    }

    @Override
    public Field<String> field6() {
        return CartLineItem.CART_LINE_ITEM.COVER;
    }

    @Override
    public Field<String> field7() {
        return CartLineItem.CART_LINE_ITEM.ITEM_KEY;
    }

    @Override
    public Field<Byte> field8() {
        return CartLineItem.CART_LINE_ITEM.STATUS;
    }

    @Override
    public Field<BigDecimal> field9() {
        return CartLineItem.CART_LINE_ITEM.SUBTOTAL;
    }

    @Override
    public Field<BigDecimal> field10() {
        return CartLineItem.CART_LINE_ITEM.TOTAL_DISCOUNTS;
    }

    @Override
    public Field<BigDecimal> field11() {
        return CartLineItem.CART_LINE_ITEM.TOTAL_PRICE;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return CartLineItem.CART_LINE_ITEM.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return CartLineItem.CART_LINE_ITEM.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCartId();
    }

    @Override
    public Long component3() {
        return getBookId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public BigDecimal component5() {
        return getPrice();
    }

    @Override
    public String component6() {
        return getCover();
    }

    @Override
    public String component7() {
        return getItemKey();
    }

    @Override
    public Byte component8() {
        return getStatus();
    }

    @Override
    public BigDecimal component9() {
        return getSubtotal();
    }

    @Override
    public BigDecimal component10() {
        return getTotalDiscounts();
    }

    @Override
    public BigDecimal component11() {
        return getTotalPrice();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component13() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCartId();
    }

    @Override
    public Long value3() {
        return getBookId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public BigDecimal value5() {
        return getPrice();
    }

    @Override
    public String value6() {
        return getCover();
    }

    @Override
    public String value7() {
        return getItemKey();
    }

    @Override
    public Byte value8() {
        return getStatus();
    }

    @Override
    public BigDecimal value9() {
        return getSubtotal();
    }

    @Override
    public BigDecimal value10() {
        return getTotalDiscounts();
    }

    @Override
    public BigDecimal value11() {
        return getTotalPrice();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value13() {
        return getUpdatedAt();
    }

    @Override
    public CartLineItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CartLineItemRecord value2(Long value) {
        setCartId(value);
        return this;
    }

    @Override
    public CartLineItemRecord value3(Long value) {
        setBookId(value);
        return this;
    }

    @Override
    public CartLineItemRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public CartLineItemRecord value5(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public CartLineItemRecord value6(String value) {
        setCover(value);
        return this;
    }

    @Override
    public CartLineItemRecord value7(String value) {
        setItemKey(value);
        return this;
    }

    @Override
    public CartLineItemRecord value8(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public CartLineItemRecord value9(BigDecimal value) {
        setSubtotal(value);
        return this;
    }

    @Override
    public CartLineItemRecord value10(BigDecimal value) {
        setTotalDiscounts(value);
        return this;
    }

    @Override
    public CartLineItemRecord value11(BigDecimal value) {
        setTotalPrice(value);
        return this;
    }

    @Override
    public CartLineItemRecord value12(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CartLineItemRecord value13(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public CartLineItemRecord values(Long value1, Long value2, Long value3, String value4, BigDecimal value5, String value6, String value7, Byte value8, BigDecimal value9, BigDecimal value10, BigDecimal value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CartLineItemRecord
     */
    public CartLineItemRecord() {
        super(CartLineItem.CART_LINE_ITEM);
    }

    /**
     * Create a detached, initialised CartLineItemRecord
     */
    public CartLineItemRecord(Long id, Long cartId, Long bookId, String name, BigDecimal price, String cover, String itemKey, Byte status, BigDecimal subtotal, BigDecimal totalDiscounts, BigDecimal totalPrice, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(CartLineItem.CART_LINE_ITEM);

        setId(id);
        setCartId(cartId);
        setBookId(bookId);
        setName(name);
        setPrice(price);
        setCover(cover);
        setItemKey(itemKey);
        setStatus(status);
        setSubtotal(subtotal);
        setTotalDiscounts(totalDiscounts);
        setTotalPrice(totalPrice);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
