/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.model.tables.records;


import com.bcorp.polaris.core.model.tables.File;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> implements Record13<Long, String, String, String, Long, Integer, Integer, String, String, Long, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>polaris-db.file.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>polaris-db.file.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>polaris-db.file.name</code>. 檔案名稱
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>polaris-db.file.name</code>. 檔案名稱
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>polaris-db.file.extension</code>. 檔案 ext
     */
    public void setExtension(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>polaris-db.file.extension</code>. 檔案 ext
     */
    public String getExtension() {
        return (String) get(2);
    }

    /**
     * Setter for <code>polaris-db.file.url</code>. 檔案 url
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>polaris-db.file.url</code>. 檔案 url
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>polaris-db.file.file_size</code>. 檔案大小
     */
    public void setFileSize(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>polaris-db.file.file_size</code>. 檔案大小
     */
    public Long getFileSize() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>polaris-db.file.width</code>. 圖片寬度
     */
    public void setWidth(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>polaris-db.file.width</code>. 圖片寬度
     */
    public Integer getWidth() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>polaris-db.file.height</code>. 圖片高度
     */
    public void setHeight(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>polaris-db.file.height</code>. 圖片高度
     */
    public Integer getHeight() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>polaris-db.file.original_filename</code>. 檔案名稱
     */
    public void setOriginalFilename(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>polaris-db.file.original_filename</code>. 檔案名稱
     */
    public String getOriginalFilename() {
        return (String) get(7);
    }

    /**
     * Setter for <code>polaris-db.file.mime_type</code>. 檔案 mime
     */
    public void setMimeType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>polaris-db.file.mime_type</code>. 檔案 mime
     */
    public String getMimeType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>polaris-db.file.user_id</code>. User id
     */
    public void setUserId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>polaris-db.file.user_id</code>. User id
     */
    public Long getUserId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>polaris-db.file.is_deleted</code>. 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public void setIsDeleted(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>polaris-db.file.is_deleted</code>. 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public Byte getIsDeleted() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>polaris-db.file.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>polaris-db.file.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>polaris-db.file.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>polaris-db.file.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, Long, Integer, Integer, String, String, Long, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, String, Long, Integer, Integer, String, String, Long, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return File.FILE.ID;
    }

    @Override
    public Field<String> field2() {
        return File.FILE.NAME;
    }

    @Override
    public Field<String> field3() {
        return File.FILE.EXTENSION;
    }

    @Override
    public Field<String> field4() {
        return File.FILE.URL;
    }

    @Override
    public Field<Long> field5() {
        return File.FILE.FILE_SIZE;
    }

    @Override
    public Field<Integer> field6() {
        return File.FILE.WIDTH;
    }

    @Override
    public Field<Integer> field7() {
        return File.FILE.HEIGHT;
    }

    @Override
    public Field<String> field8() {
        return File.FILE.ORIGINAL_FILENAME;
    }

    @Override
    public Field<String> field9() {
        return File.FILE.MIME_TYPE;
    }

    @Override
    public Field<Long> field10() {
        return File.FILE.USER_ID;
    }

    @Override
    public Field<Byte> field11() {
        return File.FILE.IS_DELETED;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return File.FILE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return File.FILE.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getExtension();
    }

    @Override
    public String component4() {
        return getUrl();
    }

    @Override
    public Long component5() {
        return getFileSize();
    }

    @Override
    public Integer component6() {
        return getWidth();
    }

    @Override
    public Integer component7() {
        return getHeight();
    }

    @Override
    public String component8() {
        return getOriginalFilename();
    }

    @Override
    public String component9() {
        return getMimeType();
    }

    @Override
    public Long component10() {
        return getUserId();
    }

    @Override
    public Byte component11() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component13() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getExtension();
    }

    @Override
    public String value4() {
        return getUrl();
    }

    @Override
    public Long value5() {
        return getFileSize();
    }

    @Override
    public Integer value6() {
        return getWidth();
    }

    @Override
    public Integer value7() {
        return getHeight();
    }

    @Override
    public String value8() {
        return getOriginalFilename();
    }

    @Override
    public String value9() {
        return getMimeType();
    }

    @Override
    public Long value10() {
        return getUserId();
    }

    @Override
    public Byte value11() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value13() {
        return getUpdatedAt();
    }

    @Override
    public FileRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FileRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public FileRecord value3(String value) {
        setExtension(value);
        return this;
    }

    @Override
    public FileRecord value4(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public FileRecord value5(Long value) {
        setFileSize(value);
        return this;
    }

    @Override
    public FileRecord value6(Integer value) {
        setWidth(value);
        return this;
    }

    @Override
    public FileRecord value7(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public FileRecord value8(String value) {
        setOriginalFilename(value);
        return this;
    }

    @Override
    public FileRecord value9(String value) {
        setMimeType(value);
        return this;
    }

    @Override
    public FileRecord value10(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public FileRecord value11(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public FileRecord value12(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FileRecord value13(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FileRecord values(Long value1, String value2, String value3, String value4, Long value5, Integer value6, Integer value7, String value8, String value9, Long value10, Byte value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(File.FILE);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(Long id, String name, String extension, String url, Long fileSize, Integer width, Integer height, String originalFilename, String mimeType, Long userId, Byte isDeleted, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(File.FILE);

        setId(id);
        setName(name);
        setExtension(extension);
        setUrl(url);
        setFileSize(fileSize);
        setWidth(width);
        setHeight(height);
        setOriginalFilename(originalFilename);
        setMimeType(mimeType);
        setUserId(userId);
        setIsDeleted(isDeleted);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
