/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.model.tables.records;


import com.bcorp.polaris.core.model.tables.OrderInvoice;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderInvoiceRecord extends UpdatableRecordImpl<OrderInvoiceRecord> implements Record14<Long, Byte, String, String, String, String, String, LocalDateTime, String, String, Byte, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>polaris-db.order_invoice.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.invoice_type</code>.
     * 發票類型，1-個人，2-公司，3-捐贈
     */
    public void setInvoiceType(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.invoice_type</code>.
     * 發票類型，1-個人，2-公司，3-捐贈
     */
    public Byte getInvoiceType() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.invoice_title</code>. 發票抬頭
     */
    public void setInvoiceTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.invoice_title</code>. 發票抬頭
     */
    public String getInvoiceTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.business_number</code>. 統一編號
     */
    public void setBusinessNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.business_number</code>. 統一編號
     */
    public String getBusinessNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.contact_email</code>. 聯絡信箱
     */
    public void setContactEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.contact_email</code>. 聯絡信箱
     */
    public String getContactEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.love_code</code>. 捐贈碼
     */
    public void setLoveCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.love_code</code>. 捐贈碼
     */
    public String getLoveCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.invoice_number</code>. 發票號碼
     */
    public void setInvoiceNumber(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.invoice_number</code>. 發票號碼
     */
    public String getInvoiceNumber() {
        return (String) get(6);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.invoice_date</code>. 發票開立日期
     */
    public void setInvoiceDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.invoice_date</code>. 發票開立日期
     */
    public LocalDateTime getInvoiceDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.order_code</code>. 對應訂單編號
     */
    public void setOrderCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.order_code</code>. 對應訂單編號
     */
    public String getOrderCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.gateway_message</code>. Gateway
     * 回傳訊息
     */
    public void setGatewayMessage(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.gateway_message</code>. Gateway
     * 回傳訊息
     */
    public String getGatewayMessage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.invoice_status</code>. 發票開立狀態
     * 1-SUCCESS, 2-FAILURE, 3-PENDING, 4-VOIDED
     */
    public void setInvoiceStatus(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.invoice_status</code>. 發票開立狀態
     * 1-SUCCESS, 2-FAILURE, 3-PENDING, 4-VOIDED
     */
    public Byte getInvoiceStatus() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.is_deleted</code>. 訂單發票禁止刪除
     */
    public void setIsDeleted(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.is_deleted</code>. 訂單發票禁止刪除
     */
    public Byte getIsDeleted() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>polaris-db.order_invoice.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>polaris-db.order_invoice.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, Byte, String, String, String, String, String, LocalDateTime, String, String, Byte, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, Byte, String, String, String, String, String, LocalDateTime, String, String, Byte, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OrderInvoice.ORDER_INVOICE.ID;
    }

    @Override
    public Field<Byte> field2() {
        return OrderInvoice.ORDER_INVOICE.INVOICE_TYPE;
    }

    @Override
    public Field<String> field3() {
        return OrderInvoice.ORDER_INVOICE.INVOICE_TITLE;
    }

    @Override
    public Field<String> field4() {
        return OrderInvoice.ORDER_INVOICE.BUSINESS_NUMBER;
    }

    @Override
    public Field<String> field5() {
        return OrderInvoice.ORDER_INVOICE.CONTACT_EMAIL;
    }

    @Override
    public Field<String> field6() {
        return OrderInvoice.ORDER_INVOICE.LOVE_CODE;
    }

    @Override
    public Field<String> field7() {
        return OrderInvoice.ORDER_INVOICE.INVOICE_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return OrderInvoice.ORDER_INVOICE.INVOICE_DATE;
    }

    @Override
    public Field<String> field9() {
        return OrderInvoice.ORDER_INVOICE.ORDER_CODE;
    }

    @Override
    public Field<String> field10() {
        return OrderInvoice.ORDER_INVOICE.GATEWAY_MESSAGE;
    }

    @Override
    public Field<Byte> field11() {
        return OrderInvoice.ORDER_INVOICE.INVOICE_STATUS;
    }

    @Override
    public Field<Byte> field12() {
        return OrderInvoice.ORDER_INVOICE.IS_DELETED;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return OrderInvoice.ORDER_INVOICE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return OrderInvoice.ORDER_INVOICE.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getInvoiceType();
    }

    @Override
    public String component3() {
        return getInvoiceTitle();
    }

    @Override
    public String component4() {
        return getBusinessNumber();
    }

    @Override
    public String component5() {
        return getContactEmail();
    }

    @Override
    public String component6() {
        return getLoveCode();
    }

    @Override
    public String component7() {
        return getInvoiceNumber();
    }

    @Override
    public LocalDateTime component8() {
        return getInvoiceDate();
    }

    @Override
    public String component9() {
        return getOrderCode();
    }

    @Override
    public String component10() {
        return getGatewayMessage();
    }

    @Override
    public Byte component11() {
        return getInvoiceStatus();
    }

    @Override
    public Byte component12() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime component13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getInvoiceType();
    }

    @Override
    public String value3() {
        return getInvoiceTitle();
    }

    @Override
    public String value4() {
        return getBusinessNumber();
    }

    @Override
    public String value5() {
        return getContactEmail();
    }

    @Override
    public String value6() {
        return getLoveCode();
    }

    @Override
    public String value7() {
        return getInvoiceNumber();
    }

    @Override
    public LocalDateTime value8() {
        return getInvoiceDate();
    }

    @Override
    public String value9() {
        return getOrderCode();
    }

    @Override
    public String value10() {
        return getGatewayMessage();
    }

    @Override
    public Byte value11() {
        return getInvoiceStatus();
    }

    @Override
    public Byte value12() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime value13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdatedAt();
    }

    @Override
    public OrderInvoiceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value2(Byte value) {
        setInvoiceType(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value3(String value) {
        setInvoiceTitle(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value4(String value) {
        setBusinessNumber(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value5(String value) {
        setContactEmail(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value6(String value) {
        setLoveCode(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value7(String value) {
        setInvoiceNumber(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value8(LocalDateTime value) {
        setInvoiceDate(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value9(String value) {
        setOrderCode(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value10(String value) {
        setGatewayMessage(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value11(Byte value) {
        setInvoiceStatus(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value12(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value13(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord value14(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public OrderInvoiceRecord values(Long value1, Byte value2, String value3, String value4, String value5, String value6, String value7, LocalDateTime value8, String value9, String value10, Byte value11, Byte value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderInvoiceRecord
     */
    public OrderInvoiceRecord() {
        super(OrderInvoice.ORDER_INVOICE);
    }

    /**
     * Create a detached, initialised OrderInvoiceRecord
     */
    public OrderInvoiceRecord(Long id, Byte invoiceType, String invoiceTitle, String businessNumber, String contactEmail, String loveCode, String invoiceNumber, LocalDateTime invoiceDate, String orderCode, String gatewayMessage, Byte invoiceStatus, Byte isDeleted, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(OrderInvoice.ORDER_INVOICE);

        setId(id);
        setInvoiceType(invoiceType);
        setInvoiceTitle(invoiceTitle);
        setBusinessNumber(businessNumber);
        setContactEmail(contactEmail);
        setLoveCode(loveCode);
        setInvoiceNumber(invoiceNumber);
        setInvoiceDate(invoiceDate);
        setOrderCode(orderCode);
        setGatewayMessage(gatewayMessage);
        setInvoiceStatus(invoiceStatus);
        setIsDeleted(isDeleted);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
