/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.model.tables;


import com.bcorp.polaris.core.model.Keys;
import com.bcorp.polaris.core.model.PolarisDb;
import com.bcorp.polaris.core.model.tables.records.OrderInvoiceRecord;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderInvoice extends TableImpl<OrderInvoiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>polaris-db.order_invoice</code>
     */
    public static final OrderInvoice ORDER_INVOICE = new OrderInvoice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderInvoiceRecord> getRecordType() {
        return OrderInvoiceRecord.class;
    }

    /**
     * The column <code>polaris-db.order_invoice.id</code>.
     */
    public final TableField<OrderInvoiceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>polaris-db.order_invoice.invoice_type</code>.
     * 發票類型，1-個人，2-公司，3-捐贈
     */
    public final TableField<OrderInvoiceRecord, Byte> INVOICE_TYPE = createField(DSL.name("invoice_type"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "發票類型，1-個人，2-公司，3-捐贈");

    /**
     * The column <code>polaris-db.order_invoice.invoice_title</code>. 發票抬頭
     */
    public final TableField<OrderInvoiceRecord, String> INVOICE_TITLE = createField(DSL.name("invoice_title"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "發票抬頭");

    /**
     * The column <code>polaris-db.order_invoice.business_number</code>. 統一編號
     */
    public final TableField<OrderInvoiceRecord, String> BUSINESS_NUMBER = createField(DSL.name("business_number"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "統一編號");

    /**
     * The column <code>polaris-db.order_invoice.contact_email</code>. 聯絡信箱
     */
    public final TableField<OrderInvoiceRecord, String> CONTACT_EMAIL = createField(DSL.name("contact_email"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "聯絡信箱");

    /**
     * The column <code>polaris-db.order_invoice.love_code</code>. 捐贈碼
     */
    public final TableField<OrderInvoiceRecord, String> LOVE_CODE = createField(DSL.name("love_code"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "捐贈碼");

    /**
     * The column <code>polaris-db.order_invoice.invoice_number</code>. 發票號碼
     */
    public final TableField<OrderInvoiceRecord, String> INVOICE_NUMBER = createField(DSL.name("invoice_number"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "發票號碼");

    /**
     * The column <code>polaris-db.order_invoice.invoice_date</code>. 發票開立日期
     */
    public final TableField<OrderInvoiceRecord, LocalDateTime> INVOICE_DATE = createField(DSL.name("invoice_date"), SQLDataType.LOCALDATETIME(0), this, "發票開立日期");

    /**
     * The column <code>polaris-db.order_invoice.order_code</code>. 對應訂單編號
     */
    public final TableField<OrderInvoiceRecord, String> ORDER_CODE = createField(DSL.name("order_code"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "對應訂單編號");

    /**
     * The column <code>polaris-db.order_invoice.gateway_message</code>. Gateway
     * 回傳訊息
     */
    public final TableField<OrderInvoiceRecord, String> GATEWAY_MESSAGE = createField(DSL.name("gateway_message"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "Gateway 回傳訊息");

    /**
     * The column <code>polaris-db.order_invoice.invoice_status</code>. 發票開立狀態
     * 1-SUCCESS, 2-FAILURE, 3-PENDING, 4-VOIDED
     */
    public final TableField<OrderInvoiceRecord, Byte> INVOICE_STATUS = createField(DSL.name("invoice_status"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "發票開立狀態 1-SUCCESS, 2-FAILURE, 3-PENDING, 4-VOIDED");

    /**
     * The column <code>polaris-db.order_invoice.is_deleted</code>. 訂單發票禁止刪除
     */
    public final TableField<OrderInvoiceRecord, Byte> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "訂單發票禁止刪除");

    /**
     * The column <code>polaris-db.order_invoice.created_at</code>. 建立時間
     */
    public final TableField<OrderInvoiceRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "建立時間");

    /**
     * The column <code>polaris-db.order_invoice.updated_at</code>. 修改時間
     */
    public final TableField<OrderInvoiceRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "修改時間");

    private OrderInvoice(Name alias, Table<OrderInvoiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderInvoice(Name alias, Table<OrderInvoiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>polaris-db.order_invoice</code> table reference
     */
    public OrderInvoice(String alias) {
        this(DSL.name(alias), ORDER_INVOICE);
    }

    /**
     * Create an aliased <code>polaris-db.order_invoice</code> table reference
     */
    public OrderInvoice(Name alias) {
        this(alias, ORDER_INVOICE);
    }

    /**
     * Create a <code>polaris-db.order_invoice</code> table reference
     */
    public OrderInvoice() {
        this(DSL.name("order_invoice"), null);
    }

    public <O extends Record> OrderInvoice(Table<O> child, ForeignKey<O, OrderInvoiceRecord> key) {
        super(child, key, ORDER_INVOICE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PolarisDb.POLARIS_DB;
    }

    @Override
    public Identity<OrderInvoiceRecord, Long> getIdentity() {
        return (Identity<OrderInvoiceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrderInvoiceRecord> getPrimaryKey() {
        return Keys.KEY_ORDER_INVOICE_PRIMARY;
    }

    @Override
    public OrderInvoice as(String alias) {
        return new OrderInvoice(DSL.name(alias), this);
    }

    @Override
    public OrderInvoice as(Name alias) {
        return new OrderInvoice(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderInvoice rename(String name) {
        return new OrderInvoice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderInvoice rename(Name name) {
        return new OrderInvoice(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, Byte, String, String, String, String, String, LocalDateTime, String, String, Byte, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
