/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.model.tables.daos;


import com.bcorp.polaris.model.tables.Chapter;
import com.bcorp.polaris.model.tables.records.ChapterRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ChapterDao extends DAOImpl<ChapterRecord, com.bcorp.polaris.model.tables.pojos.Chapter, ULong> {

    /**
     * Create a new ChapterDao without any configuration
     */
    public ChapterDao() {
        super(Chapter.CHAPTER, com.bcorp.polaris.model.tables.pojos.Chapter.class);
    }

    /**
     * Create a new ChapterDao with an attached configuration
     */
    @Autowired
    public ChapterDao(Configuration configuration) {
        super(Chapter.CHAPTER, com.bcorp.polaris.model.tables.pojos.Chapter.class, configuration);
    }

    @Override
    public ULong getId(com.bcorp.polaris.model.tables.pojos.Chapter object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Chapter.CHAPTER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchById(ULong... values) {
        return fetch(Chapter.CHAPTER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.bcorp.polaris.model.tables.pojos.Chapter fetchOneById(ULong value) {
        return fetchOne(Chapter.CHAPTER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.bcorp.polaris.model.tables.pojos.Chapter> fetchOptionalById(ULong value) {
        return fetchOptional(Chapter.CHAPTER.ID, value);
    }

    /**
     * Fetch records that have <code>book_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchRangeOfBookId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(Chapter.CHAPTER.BOOK_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchByBookId(ULong... values) {
        return fetch(Chapter.CHAPTER.BOOK_ID, values);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Chapter.CHAPTER.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchByTitle(String... values) {
        return fetch(Chapter.CHAPTER.TITLE, values);
    }

    /**
     * Fetch records that have <code>sort_position BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchRangeOfSortPosition(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Chapter.CHAPTER.SORT_POSITION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort_position IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchBySortPosition(Integer... values) {
        return fetch(Chapter.CHAPTER.SORT_POSITION, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchRangeOfIsDeleted(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(Chapter.CHAPTER.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchByIsDeleted(UByte... values) {
        return fetch(Chapter.CHAPTER.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Chapter.CHAPTER.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(Chapter.CHAPTER.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Chapter.CHAPTER.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.Chapter> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(Chapter.CHAPTER.UPDATED_AT, values);
    }
}
