/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.model.tables.daos;


import com.bcorp.polaris.model.tables.PaymentMode;
import com.bcorp.polaris.model.tables.records.PaymentModeRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PaymentModeDao extends DAOImpl<PaymentModeRecord, com.bcorp.polaris.model.tables.pojos.PaymentMode, ULong> {

    /**
     * Create a new PaymentModeDao without any configuration
     */
    public PaymentModeDao() {
        super(PaymentMode.PAYMENT_MODE, com.bcorp.polaris.model.tables.pojos.PaymentMode.class);
    }

    /**
     * Create a new PaymentModeDao with an attached configuration
     */
    @Autowired
    public PaymentModeDao(Configuration configuration) {
        super(PaymentMode.PAYMENT_MODE, com.bcorp.polaris.model.tables.pojos.PaymentMode.class, configuration);
    }

    @Override
    public ULong getId(com.bcorp.polaris.model.tables.pojos.PaymentMode object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(PaymentMode.PAYMENT_MODE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchById(ULong... values) {
        return fetch(PaymentMode.PAYMENT_MODE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.bcorp.polaris.model.tables.pojos.PaymentMode fetchOneById(ULong value) {
        return fetchOne(PaymentMode.PAYMENT_MODE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchOptionalById(ULong value) {
        return fetchOptional(PaymentMode.PAYMENT_MODE.ID, value);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchRangeOfCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(PaymentMode.PAYMENT_MODE.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchByCode(String... values) {
        return fetch(PaymentMode.PAYMENT_MODE.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>code = value</code>
     */
    public com.bcorp.polaris.model.tables.pojos.PaymentMode fetchOneByCode(String value) {
        return fetchOne(PaymentMode.PAYMENT_MODE.CODE, value);
    }

    /**
     * Fetch a unique record that has <code>code = value</code>
     */
    public Optional<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchOptionalByCode(String value) {
        return fetchOptional(PaymentMode.PAYMENT_MODE.CODE, value);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(PaymentMode.PAYMENT_MODE.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchByDescription(String... values) {
        return fetch(PaymentMode.PAYMENT_MODE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchRangeOfIsActive(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(PaymentMode.PAYMENT_MODE.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchByIsActive(UByte... values) {
        return fetch(PaymentMode.PAYMENT_MODE.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchRangeOfIsDeleted(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(PaymentMode.PAYMENT_MODE.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchByIsDeleted(UByte... values) {
        return fetch(PaymentMode.PAYMENT_MODE.IS_DELETED, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(PaymentMode.PAYMENT_MODE.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(PaymentMode.PAYMENT_MODE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(PaymentMode.PAYMENT_MODE.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.bcorp.polaris.model.tables.pojos.PaymentMode> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(PaymentMode.PAYMENT_MODE.UPDATED_AT, values);
    }
}
