/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.dto;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;


@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderDto
{
    private Long id;
    private Long userId;
    private Long invoiceId;
    private String code;
    private String orderStatus;
    private BigDecimal subtotal;
    private BigDecimal totalDiscounts;
    private BigDecimal totalPrice;
    private String paymentMode;
    private String paymentStatus;
    private LocalDateTime payAt;
    private LocalDateTime completeAt;
    private Byte isDeleted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
