/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.core.model;


import com.bcorp.polaris.core.model.tables.*;


/**
 * Convenience access to all tables in polaris-db.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables
{

    /**
     * The table <code>polaris-db.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>polaris-db.book_category</code>.
     */
    public static final BookCategory BOOK_CATEGORY = BookCategory.BOOK_CATEGORY;

    /**
     * The table <code>polaris-db.book_review</code>.
     */
    public static final BookReview BOOK_REVIEW = BookReview.BOOK_REVIEW;

    /**
     * The table <code>polaris-db.cart</code>.
     */
    public static final Cart CART = Cart.CART;

    /**
     * The table <code>polaris-db.cart_line_item</code>.
     */
    public static final CartLineItem CART_LINE_ITEM = CartLineItem.CART_LINE_ITEM;

    /**
     * The table <code>polaris-db.chapter</code>.
     */
    public static final Chapter CHAPTER = Chapter.CHAPTER;

    /**
     * The table <code>polaris-db.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>polaris-db.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>polaris-db.order_line_item</code>.
     */
    public static final OrderLineItem ORDER_LINE_ITEM = OrderLineItem.ORDER_LINE_ITEM;

    /**
     * The table <code>polaris-db.page</code>.
     */
    public static final Page PAGE = Page.PAGE;

    /**
     * The table <code>polaris-db.payment_mode</code>.
     */
    public static final PaymentMode PAYMENT_MODE = PaymentMode.PAYMENT_MODE;

    /**
     * The table <code>polaris-db.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>polaris-db.user_bookshelf</code>.
     */
    public static final UserBookshelf USER_BOOKSHELF = UserBookshelf.USER_BOOKSHELF;
}
