/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookReview implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong         id;
    private String        comment;
    private ULong         userId;
    private ULong         bookId;
    private UByte         ratingStar;
    private UByte         isDeleted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public BookReview() {}

    public BookReview(BookReview value) {
        this.id = value.id;
        this.comment = value.comment;
        this.userId = value.userId;
        this.bookId = value.bookId;
        this.ratingStar = value.ratingStar;
        this.isDeleted = value.isDeleted;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public BookReview(
        ULong         id,
        String        comment,
        ULong         userId,
        ULong         bookId,
        UByte         ratingStar,
        UByte         isDeleted,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.comment = comment;
        this.userId = userId;
        this.bookId = bookId;
        this.ratingStar = ratingStar;
        this.isDeleted = isDeleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>polaris-db.book_review.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>polaris-db.book_review.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>polaris-db.book_review.comment</code>. 留言內容
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>polaris-db.book_review.comment</code>. 留言內容
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for <code>polaris-db.book_review.user_id</code>. 使用者 id
     */
    public ULong getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>polaris-db.book_review.user_id</code>. 使用者 id
     */
    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>polaris-db.book_review.book_id</code>. 書本   id
     */
    public ULong getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>polaris-db.book_review.book_id</code>. 書本   id
     */
    public void setBookId(ULong bookId) {
        this.bookId = bookId;
    }

    /**
     * Getter for <code>polaris-db.book_review.rating_star</code>. 評分 0 ~ 5
     */
    public UByte getRatingStar() {
        return this.ratingStar;
    }

    /**
     * Setter for <code>polaris-db.book_review.rating_star</code>. 評分 0 ~ 5
     */
    public void setRatingStar(UByte ratingStar) {
        this.ratingStar = ratingStar;
    }

    /**
     * Getter for <code>polaris-db.book_review.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public UByte getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>polaris-db.book_review.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public void setIsDeleted(UByte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>polaris-db.book_review.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>polaris-db.book_review.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>polaris-db.book_review.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>polaris-db.book_review.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookReview (");

        sb.append(id);
        sb.append(", ").append(comment);
        sb.append(", ").append(userId);
        sb.append(", ").append(bookId);
        sb.append(", ").append(ratingStar);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
