/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cart implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong         id;
    private String        code;
    private BigDecimal    subtotal;
    private BigDecimal    totalPrice;
    private BigDecimal    totalDiscounts;
    private ULong         userId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Cart() {}

    public Cart(Cart value) {
        this.id = value.id;
        this.code = value.code;
        this.subtotal = value.subtotal;
        this.totalPrice = value.totalPrice;
        this.totalDiscounts = value.totalDiscounts;
        this.userId = value.userId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Cart(
        ULong         id,
        String        code,
        BigDecimal    subtotal,
        BigDecimal    totalPrice,
        BigDecimal    totalDiscounts,
        ULong         userId,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.code = code;
        this.subtotal = subtotal;
        this.totalPrice = totalPrice;
        this.totalDiscounts = totalDiscounts;
        this.userId = userId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>polaris-db.cart.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>polaris-db.cart.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>polaris-db.cart.code</code>. 購物車編號
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>polaris-db.cart.code</code>. 購物車編號
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>polaris-db.cart.subtotal</code>. 購物車小計
     */
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    /**
     * Setter for <code>polaris-db.cart.subtotal</code>. 購物車小計
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * Getter for <code>polaris-db.cart.total_price</code>. 購物車總金額
     */
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    /**
     * Setter for <code>polaris-db.cart.total_price</code>. 購物車總金額
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * Getter for <code>polaris-db.cart.total_discounts</code>. 購物車總折扣
     */
    public BigDecimal getTotalDiscounts() {
        return this.totalDiscounts;
    }

    /**
     * Setter for <code>polaris-db.cart.total_discounts</code>. 購物車總折扣
     */
    public void setTotalDiscounts(BigDecimal totalDiscounts) {
        this.totalDiscounts = totalDiscounts;
    }

    /**
     * Getter for <code>polaris-db.cart.user_id</code>. 使用者 id
     */
    public ULong getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>polaris-db.cart.user_id</code>. 使用者 id
     */
    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>polaris-db.cart.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>polaris-db.cart.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>polaris-db.cart.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>polaris-db.cart.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Cart (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(subtotal);
        sb.append(", ").append(totalPrice);
        sb.append(", ").append(totalDiscounts);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
