/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderLineItem implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong         id;
    private ULong         orderId;
    private ULong         bookId;
    private String        name;
    private BigDecimal    price;
    private Integer       quantity;
    private BigDecimal    subtotal;
    private BigDecimal    totalDiscounts;
    private BigDecimal    totalPrice;
    private UByte         isDeleted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public OrderLineItem() {}

    public OrderLineItem(OrderLineItem value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.bookId = value.bookId;
        this.name = value.name;
        this.price = value.price;
        this.quantity = value.quantity;
        this.subtotal = value.subtotal;
        this.totalDiscounts = value.totalDiscounts;
        this.totalPrice = value.totalPrice;
        this.isDeleted = value.isDeleted;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public OrderLineItem(
        ULong         id,
        ULong         orderId,
        ULong         bookId,
        String        name,
        BigDecimal    price,
        Integer       quantity,
        BigDecimal    subtotal,
        BigDecimal    totalDiscounts,
        BigDecimal    totalPrice,
        UByte         isDeleted,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.orderId = orderId;
        this.bookId = bookId;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
        this.subtotal = subtotal;
        this.totalDiscounts = totalDiscounts;
        this.totalPrice = totalPrice;
        this.isDeleted = isDeleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.order_id</code>.
     */
    public ULong getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.order_id</code>.
     */
    public void setOrderId(ULong orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.book_id</code>.
     */
    public ULong getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.book_id</code>.
     */
    public void setBookId(ULong bookId) {
        this.bookId = bookId;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.name</code>. 商品名稱
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.name</code>. 商品名稱
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.price</code>. 商品金額
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.price</code>. 商品金額
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.quantity</code>.
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.quantity</code>.
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.subtotal</code>. 商品小計
     */
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.subtotal</code>. 商品小計
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.total_discounts</code>. 商品總折扣
     */
    public BigDecimal getTotalDiscounts() {
        return this.totalDiscounts;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.total_discounts</code>. 商品總折扣
     */
    public void setTotalDiscounts(BigDecimal totalDiscounts) {
        this.totalDiscounts = totalDiscounts;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.total_price</code>. 商品總金額
     */
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.total_price</code>. 商品總金額
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.is_deleted</code>. 訂單商品禁止刪除
     */
    public UByte getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.is_deleted</code>. 訂單商品禁止刪除
     */
    public void setIsDeleted(UByte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>polaris-db.order_line_item.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>polaris-db.order_line_item.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderLineItem (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(bookId);
        sb.append(", ").append(name);
        sb.append(", ").append(price);
        sb.append(", ").append(quantity);
        sb.append(", ").append(subtotal);
        sb.append(", ").append(totalDiscounts);
        sb.append(", ").append(totalPrice);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
