/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong         id;
    private ULong         userId;
    private ULong         invoiceId;
    private String        code;
    private UByte         orderStatus;
    private BigDecimal    subtotal;
    private BigDecimal    totalDiscounts;
    private BigDecimal    totalPrice;
    private ULong         paymentModeId;
    private UByte         paymentStatus;
    private LocalDateTime payAt;
    private LocalDateTime completeAt;
    private UByte         isDeleted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Order() {}

    public Order(Order value) {
        this.id = value.id;
        this.userId = value.userId;
        this.invoiceId = value.invoiceId;
        this.code = value.code;
        this.orderStatus = value.orderStatus;
        this.subtotal = value.subtotal;
        this.totalDiscounts = value.totalDiscounts;
        this.totalPrice = value.totalPrice;
        this.paymentModeId = value.paymentModeId;
        this.paymentStatus = value.paymentStatus;
        this.payAt = value.payAt;
        this.completeAt = value.completeAt;
        this.isDeleted = value.isDeleted;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Order(
        ULong         id,
        ULong         userId,
        ULong         invoiceId,
        String        code,
        UByte         orderStatus,
        BigDecimal    subtotal,
        BigDecimal    totalDiscounts,
        BigDecimal    totalPrice,
        ULong         paymentModeId,
        UByte         paymentStatus,
        LocalDateTime payAt,
        LocalDateTime completeAt,
        UByte         isDeleted,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.invoiceId = invoiceId;
        this.code = code;
        this.orderStatus = orderStatus;
        this.subtotal = subtotal;
        this.totalDiscounts = totalDiscounts;
        this.totalPrice = totalPrice;
        this.paymentModeId = paymentModeId;
        this.paymentStatus = paymentStatus;
        this.payAt = payAt;
        this.completeAt = completeAt;
        this.isDeleted = isDeleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>polaris-db.order.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>polaris-db.order.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>polaris-db.order.user_id</code>. 購買人 id
     */
    public ULong getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>polaris-db.order.user_id</code>. 購買人 id
     */
    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>polaris-db.order.invoice_id</code>. 發票 id
     */
    public ULong getInvoiceId() {
        return this.invoiceId;
    }

    /**
     * Setter for <code>polaris-db.order.invoice_id</code>. 發票 id
     */
    public void setInvoiceId(ULong invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * Getter for <code>polaris-db.order.code</code>. 訂單編號
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>polaris-db.order.code</code>. 訂單編號
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>polaris-db.order.order_status</code>. 訂單狀態
     */
    public UByte getOrderStatus() {
        return this.orderStatus;
    }

    /**
     * Setter for <code>polaris-db.order.order_status</code>. 訂單狀態
     */
    public void setOrderStatus(UByte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * Getter for <code>polaris-db.order.subtotal</code>. 訂單小計
     */
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    /**
     * Setter for <code>polaris-db.order.subtotal</code>. 訂單小計
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * Getter for <code>polaris-db.order.total_discounts</code>. 訂單總折扣
     */
    public BigDecimal getTotalDiscounts() {
        return this.totalDiscounts;
    }

    /**
     * Setter for <code>polaris-db.order.total_discounts</code>. 訂單總折扣
     */
    public void setTotalDiscounts(BigDecimal totalDiscounts) {
        this.totalDiscounts = totalDiscounts;
    }

    /**
     * Getter for <code>polaris-db.order.total_price</code>. 訂單總金額
     */
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    /**
     * Setter for <code>polaris-db.order.total_price</code>. 訂單總金額
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * Getter for <code>polaris-db.order.payment_mode_id</code>. 付款方式
     */
    public ULong getPaymentModeId() {
        return this.paymentModeId;
    }

    /**
     * Setter for <code>polaris-db.order.payment_mode_id</code>. 付款方式
     */
    public void setPaymentModeId(ULong paymentModeId) {
        this.paymentModeId = paymentModeId;
    }

    /**
     * Getter for <code>polaris-db.order.payment_status</code>. 付款狀態
     */
    public UByte getPaymentStatus() {
        return this.paymentStatus;
    }

    /**
     * Setter for <code>polaris-db.order.payment_status</code>. 付款狀態
     */
    public void setPaymentStatus(UByte paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * Getter for <code>polaris-db.order.pay_at</code>. 付款時間
     */
    public LocalDateTime getPayAt() {
        return this.payAt;
    }

    /**
     * Setter for <code>polaris-db.order.pay_at</code>. 付款時間
     */
    public void setPayAt(LocalDateTime payAt) {
        this.payAt = payAt;
    }

    /**
     * Getter for <code>polaris-db.order.complete_at</code>. 訂單完成時間
     */
    public LocalDateTime getCompleteAt() {
        return this.completeAt;
    }

    /**
     * Setter for <code>polaris-db.order.complete_at</code>. 訂單完成時間
     */
    public void setCompleteAt(LocalDateTime completeAt) {
        this.completeAt = completeAt;
    }

    /**
     * Getter for <code>polaris-db.order.is_deleted</code>. 訂單禁止刪除
     */
    public UByte getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>polaris-db.order.is_deleted</code>. 訂單禁止刪除
     */
    public void setIsDeleted(UByte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>polaris-db.order.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>polaris-db.order.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>polaris-db.order.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>polaris-db.order.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Order (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(invoiceId);
        sb.append(", ").append(code);
        sb.append(", ").append(orderStatus);
        sb.append(", ").append(subtotal);
        sb.append(", ").append(totalDiscounts);
        sb.append(", ").append(totalPrice);
        sb.append(", ").append(paymentModeId);
        sb.append(", ").append(paymentStatus);
        sb.append(", ").append(payAt);
        sb.append(", ").append(completeAt);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
