/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentMode implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong         id;
    private String        code;
    private String        description;
    private UByte         isActive;
    private UByte         isDeleted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public PaymentMode() {}

    public PaymentMode(PaymentMode value) {
        this.id = value.id;
        this.code = value.code;
        this.description = value.description;
        this.isActive = value.isActive;
        this.isDeleted = value.isDeleted;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public PaymentMode(
        ULong         id,
        String        code,
        String        description,
        UByte         isActive,
        UByte         isDeleted,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.code = code;
        this.description = description;
        this.isActive = isActive;
        this.isDeleted = isDeleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>polaris-db.payment_mode.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>polaris-db.payment_mode.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>polaris-db.payment_mode.code</code>. 付款識別子
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>polaris-db.payment_mode.code</code>. 付款識別子
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>polaris-db.payment_mode.description</code>. 付款方式描述
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>polaris-db.payment_mode.description</code>. 付款方式描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>polaris-db.payment_mode.is_active</code>.
     * 是否啟用，0-未啟用，1-啟用，預設為 1
     */
    public UByte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>polaris-db.payment_mode.is_active</code>.
     * 是否啟用，0-未啟用，1-啟用，預設為 1
     */
    public void setIsActive(UByte isActive) {
        this.isActive = isActive;
    }

    /**
     * Getter for <code>polaris-db.payment_mode.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public UByte getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>polaris-db.payment_mode.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public void setIsDeleted(UByte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>polaris-db.payment_mode.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>polaris-db.payment_mode.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>polaris-db.payment_mode.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>polaris-db.payment_mode.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PaymentMode (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(description);
        sb.append(", ").append(isActive);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
