/*
 * This file is generated by jOOQ.
 */
package com.bcorp.polaris.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBookshelf implements Serializable {

    private static final long serialVersionUID = 1L;

    private ULong         id;
    private ULong         userId;
    private ULong         bookId;
    private ULong         lastChapterId;
    private UByte         isDeleted;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public UserBookshelf() {}

    public UserBookshelf(UserBookshelf value) {
        this.id = value.id;
        this.userId = value.userId;
        this.bookId = value.bookId;
        this.lastChapterId = value.lastChapterId;
        this.isDeleted = value.isDeleted;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public UserBookshelf(
        ULong         id,
        ULong         userId,
        ULong         bookId,
        ULong         lastChapterId,
        UByte         isDeleted,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.bookId = bookId;
        this.lastChapterId = lastChapterId;
        this.isDeleted = isDeleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>polaris-db.user_bookshelf.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Setter for <code>polaris-db.user_bookshelf.id</code>.
     */
    public void setId(ULong id) {
        this.id = id;
    }

    /**
     * Getter for <code>polaris-db.user_bookshelf.user_id</code>. 使用者 id
     */
    public ULong getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>polaris-db.user_bookshelf.user_id</code>. 使用者 id
     */
    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>polaris-db.user_bookshelf.book_id</code>. 書本 id
     */
    public ULong getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>polaris-db.user_bookshelf.book_id</code>. 書本 id
     */
    public void setBookId(ULong bookId) {
        this.bookId = bookId;
    }

    /**
     * Getter for <code>polaris-db.user_bookshelf.last_chapter_id</code>. 上次閱讀章節
     * id
     */
    public ULong getLastChapterId() {
        return this.lastChapterId;
    }

    /**
     * Setter for <code>polaris-db.user_bookshelf.last_chapter_id</code>. 上次閱讀章節
     * id
     */
    public void setLastChapterId(ULong lastChapterId) {
        this.lastChapterId = lastChapterId;
    }

    /**
     * Getter for <code>polaris-db.user_bookshelf.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public UByte getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>polaris-db.user_bookshelf.is_deleted</code>.
     * 是否刪除，0-未刪除，1-刪除，預設為 0
     */
    public void setIsDeleted(UByte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>polaris-db.user_bookshelf.created_at</code>. 建立時間
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>polaris-db.user_bookshelf.created_at</code>. 建立時間
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>polaris-db.user_bookshelf.updated_at</code>. 修改時間
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>polaris-db.user_bookshelf.updated_at</code>. 修改時間
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserBookshelf (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(bookId);
        sb.append(", ").append(lastChapterId);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
